language: python
cache: pip
python:
  - "3.5"
services:
  - postgresql
env:
  - MATE_TEST_DB_CONFIG="user=postgres dbname=mate"
before_script:
- "psql -c 'create database mate;' -U postgres"
# command to install dependencies
install:
  - "pip install -r requirements_dev.txt"
  - "pip install -r requirements.txt"
# command to run tests
script: make coverage-ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
